name: inflow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^8.0.2
  http: ^1.6.0
  pinput: ^6.0.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
